defmodule Albedo.Agents.ChangePlannerTest do
  use ExUnit.Case, async: true

  describe "ticket counting" do
    test "counts tickets from markdown" do
      content = """
      ### Ticket #1: Create user schema

      Description here.

      ### Ticket #2: Add login form

      More content.

      ### Ticket #3: Write tests
      """

      assert count_tickets(content) == 3
    end

    test "returns 0 for no tickets" do
      assert count_tickets("No tickets here") == 0
      assert count_tickets("") == 0
    end
  end

  describe "points extraction" do
    test "extracts total from summary table" do
      content = """
      | Status | Count |
      |--------|-------|
      | **Total** | **15** |
      """

      assert extract_total_points(content) == 15
    end

    test "estimates points from size keywords when no total" do
      content = """
      **Estimate:** Small
      **Estimate:** Medium
      **Estimate:** Large
      """

      assert extract_total_points(content) == 2 + 5 + 8
    end

    test "returns 0 when no points found" do
      assert extract_total_points("No estimate info") == 0
    end
  end

  describe "file counting" do
    test "counts files to create from table" do
      content = """
      #### Files to Create
      | File | Purpose |
      |------|---------|
      | lib/accounts/user.ex | User schema |
      | lib/accounts/accounts.ex | Context module |
      """

      assert count_files_to_create(content) == 2
    end

    test "counts files to modify from table" do
      content = """
      #### Files to Modify
      | File | Changes |
      |------|---------|
      | lib/router.ex | Add routes |
      | lib/app.ex | Add supervision |
      | config/config.exs | Add config |
      """

      assert count_files_to_modify(content) == 3
    end

    test "returns 0 for empty tables" do
      assert count_files_to_create("No files") == 0
      assert count_files_to_modify("No files") == 0
    end
  end

  describe "risk counting" do
    test "counts risks from summary table" do
      content = """
      ## Risk Summary

      | Risk | Severity | Mitigation |
      |------|----------|------------|
      | Database migration | High | Backup first |
      | Breaking change | Medium | Version bump |
      """

      assert count_risks(content) == 2
    end

    test "counts risks from inline mentions" do
      content = """
      | High | Risk 1 |
      | Medium | Risk 2 |
      """

      assert count_risks(content) == 2
    end

    test "returns 0 for no risks" do
      assert count_risks("No risks identified") == 0
    end
  end

  describe "research files list" do
    test "returns greenfield research files" do
      result = research_files_list(true)

      assert result =~ "00_domain_research.md"
      assert result =~ "01_tech_stack.md"
      assert result =~ "02_architecture.md"
      refute result =~ "03_conventions.md"
    end

    test "returns full research files list for existing codebase" do
      result = research_files_list(false)

      assert result =~ "00_domain_research.md"
      assert result =~ "03_conventions.md"
      assert result =~ "04_feature_location.md"
      assert result =~ "05_impact_analysis.md"
    end
  end

  describe "metadata header" do
    test "adds version and date" do
      content = "# My Plan"
      result = add_metadata_header(content, false)

      assert result =~ "Generated by Albedo"
      assert result =~ "#{Date.utc_today()}"
      assert result =~ "# My Plan"
      assert result =~ "## Appendix"
    end

    test "includes research files appendix" do
      result = add_metadata_header("Content", true)

      assert result =~ "### Research Files"
      assert result =~ "00_domain_research.md"
    end
  end

  describe "summary extraction" do
    test "extracts complete summary" do
      content = """
      ## Summary
      | **Total** | **12** |

      ### Ticket #1: First ticket
      **Estimate:** Small

      #### Files to Create
      | File | Purpose |
      |------|---------|
      | lib/user.ex | Schema |

      #### Files to Modify
      | File | Changes |
      |------|---------|
      | lib/app.ex | Add module |

      ## Risk Summary
      | Risk | Severity |
      |------|----------|
      | Migration | High |
      """

      summary = extract_summary(content)

      assert summary.tickets_count == 1
      assert summary.total_points == 12
      assert summary.files_to_create == 1
      assert summary.files_to_modify == 1
      assert summary.risks_identified == 1
    end
  end

  defp count_tickets(content) do
    Regex.scan(~r/### Ticket #\d+/, content)
    |> length()
  end

  defp extract_total_points(content) do
    case Regex.run(~r/\*\*Total\*\*.*?(\d+)/, content) do
      [_, points] -> String.to_integer(points)
      _ -> estimate_points(content)
    end
  end

  defp estimate_points(content) do
    small = length(Regex.scan(~r/Estimate.*Small/i, content)) * 2
    medium = length(Regex.scan(~r/Estimate.*Medium/i, content)) * 5
    large = length(Regex.scan(~r/Estimate.*Large/i, content)) * 8
    small + medium + large
  end

  defp count_files_to_create(content) do
    sections = Regex.scan(~r/#### Files to Create\n\|.*?\n\|.*?\n((?:\|.*?\n)*)/s, content)

    sections
    |> Enum.flat_map(fn [_, table] ->
      String.split(table, "\n", trim: true)
    end)
    |> Enum.filter(&String.starts_with?(&1, "|"))
    |> length()
  end

  defp count_files_to_modify(content) do
    sections = Regex.scan(~r/#### Files to Modify\n\|.*?\n\|.*?\n((?:\|.*?\n)*)/s, content)

    sections
    |> Enum.flat_map(fn [_, table] ->
      String.split(table, "\n", trim: true)
    end)
    |> Enum.filter(&String.starts_with?(&1, "|"))
    |> length()
  end

  defp count_risks(content) do
    risk_section =
      Regex.run(~r/## Risk Summary\n\n\|.*?\n\|.*?\n((?:\|.*?\n)*)/s, content)

    case risk_section do
      [_, table] ->
        table
        |> String.split("\n", trim: true)
        |> Enum.filter(&String.starts_with?(&1, "|"))
        |> length()

      _ ->
        length(Regex.scan(~r/\| High \||\| Medium \|/i, content))
    end
  end

  defp research_files_list(true) do
    """
    - [00_domain_research.md](./00_domain_research.md)
    - [01_tech_stack.md](./01_tech_stack.md)
    - [02_architecture.md](./02_architecture.md)
    """
  end

  defp research_files_list(false) do
    """
    - [00_domain_research.md](./00_domain_research.md)
    - [01_tech_stack.md](./01_tech_stack.md)
    - [02_architecture.md](./02_architecture.md)
    - [03_conventions.md](./03_conventions.md)
    - [04_feature_location.md](./04_feature_location.md)
    - [05_impact_analysis.md](./05_impact_analysis.md)
    """
  end

  defp add_metadata_header(content, greenfield?) do
    """
    <!-- Generated by Albedo v#{Albedo.version()} on #{Date.utc_today()} -->

    #{content}

    ---

    ## Appendix

    ### Research Files
    All research that informed this plan:

    #{research_files_list(greenfield?)}
    """
  end

  defp extract_summary(content) do
    tickets_count = count_tickets(content)
    total_points = extract_total_points(content)
    files_to_create = count_files_to_create(content)
    files_to_modify = count_files_to_modify(content)
    risks_identified = count_risks(content)

    %{
      tickets_count: tickets_count,
      total_points: total_points,
      files_to_create: files_to_create,
      files_to_modify: files_to_modify,
      risks_identified: risks_identified
    }
  end
end
